name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 200                
          repositories_forks: yes           
          repositories_affiliations: collaborator
          plugin_languages: yes
          plugin_languages_ignored: html, css 
          plugin_languages_details: bytes-size, percentage
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 30
          plugin_reactions_details: count, percentage
          plugin_gists: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3086403                           
          plugin_stackoverflow_sections: ""
          plugin_stackoverflow_limit: 2                                
          plugin_stackoverflow_lines: 4                                
          plugin_posts: yes
          plugin_posts_source: dev.to      # External source
          plugin_people_user: .github.user
